query getPhotos(
	$id: UUID
	$userId: UUID
	$username: String
	$diveSite: UUID
	$dive: UUID
	$sealifeId: UUID
	$offset: Int
	$orderByUpload: Boolean
) {
	photos(
		id: $id
		userId: $userId
		username: $username
		diveSite: $diveSite
		dive: $dive
		sealifeId: $sealifeId
		offset: $offset
		orderByUpload: $orderByUpload
	) {
		...PhotoSummary
	}
	siteUrl
}
