query getSealifeSummary(
	$id: UUID
	$name: String
	$scientificName: String
	$slug: String
	$categoryValues: [UUID!]
) {
	sealife(
		id: $id
		name: $name
		scientificName: $scientificName
		slug: $slug
		categoryValues: $categoryValues
	) {
		...SealifeSummary
	}
}

query getSealife($id: UUID, $name: String, $scientificName: String, $slug: String) {
	sealife(id: $id, name: $name, scientificName: $scientificName, slug: $slug) {
		...SealifeNode
	}
	siteUrl
}
