[package]
name = "divedb_macro"
version = "0.1.0"
edition = "2018"
license = "AGPL-3.0"

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = { version = "1", features = ["full", "parsing"] }
proc-macro2 = "1"