fragment DiveSummary on Dive {
	id
	date
	number
	numComments
	user {
		...UserSummary
	}
	diveSite {
		...SiteSummary
	}
}

fragment DiveWithMetrics on Dive {
	id
	userId
	date
	depth
	duration
	number
	hasMetrics
	summary
	likes
	liked
	numComments
	diveSite {
		...SiteSummary
	}
	latestPhotos {
		...PhotoSummary
	}
	user {
		...UserSummary
	}
}

fragment DiveNode on Dive {
	id
	userId
	date
	depth
	duration
	number
	hasMetrics
	description
	summary
	published
	likes
	liked
	numComments
	comments {
		...Comment
	}
	user {
		...UserSummary
	}
	latestPhotos {
		...PhotoSummary
	}
	diveSiteId
	diveSite {
		...SiteSummary
	}
}
