fragment PhotoSummary on Photo {
	id
	userId
	filename
	date
	size
	width
	height
	likes
	liked
	dive {
		...DiveSummary
	}
	diveSite {
		...SiteSummary
	}
	sealife {
		...SealifeSummary
	}
	user {
		...UserSummary
	}
}
