fragment CurrentUser on LoginResponse {
	id
	email
	level
	username
	displayName
	watermarkLocation
	copyrightLocation
	description
	photoId
}

fragment CurrentUserToken on LoginResponse {
	id
	email
	username
	level
	token
}

fragment UserSummary on PublicUserInfo {
	id
	username
	displayName
}

fragment UserInfo on PublicUserInfo {
	id
	username
	displayName
	description
	photoId
	photoCount
	diveCount
	latestPhotos {
		...PhotoSummary
	}
	latestDives {
		...DiveWithMetrics
	}
}
