fragment CurrentUser on LoginResponse {
	id
	email
	level
	username
	displayName
	watermarkLocation
	copyrightLocation
}

fragment CurrentUserToken on LoginResponse {
	id
	email
	username
	level
	token
}

fragment UserSummary on PublicUserInfo {
	id
	username
	displayName
}
